name: PoiemaWeb
description: Front End Web Development Tutorial
keywords: 자바스크립트, 노드, 익스프레스, HTML5, CSS3, Saaa, Javascript, node.js, express, MongoDB, SocketIO
markdown: kramdown
kramdown:
  input: GFM
exclude: ['images/original']
permalink: :title.html
sass:
  style: expanded
